### ISSUE TITLE
data in main component

### ISSUE THREAD

**Issue by Milesq** [Authman2/Mosaic#11]
```js
import Mosaic from '@authman2/mosaic';

const app = new Mosaic({
   element: '#app',
   data: {
      foo: 'ok'
   },
   view: (data) => {
      return html`<div>${ data.foo }</div>`;
   }
});

app.paint();
```

this code should display 'ok', right? He does not do this

**Comment by Authman2** [comment]
What does the html file look like? It should have an element with the id "app" otherwise it will not know where to put the component.

**Comment by Milesq** [comment]
Element #app exists. I had an old version of Mosaic. I've installed @authman2/mosaic@latest and it works;). Great freamwork, I was afraid that it will be a bit unstable but for smaller projects it is perfect!
