### ISSUE TITLE
The element passed to the paint method

### ISSUE THREAD

**Issue by Milesq** [Authman2/Mosaic#14]
Can you add the ability to pass an item to the painting method, not as an option in the Mosaic constructor?
```js
const hello = Mosaic({
  // element: '#root',
  view: () => html`<span>Hello World</span>`
});

hello.paint('#root');
hello.paint('#app');
```

**Comment by Authman2** [comment]
What would be the purpose/improvement of this over the current version? Can you give some use cases?

**Comment by Milesq** [comment]
Sometimes a developer (rare, but still ...) wants to use one freamwork object two or more times. Sometimes the developer wants to declare the Mosaic object at the first stage and then decide where to paint it. For example, Vue
```js
const app = new Vue({
// declare some options
});

app.$mount('#app');
```

**Comment by Authman2** [comment]
Ok, I was planning on adding an "additional options" property to the paint method anyway so I will include it in the next update.
