### ISSUE TITLE
do you support dynamic list of sub components?

### ISSUE THREAD

**Issue by ged-odoo** [Authman2/Mosaic#7]
I could not find how to render a list of sub components. Something like https://vuejs.org/v2/guide/list.html

How would you do to display a list of records?

**Comment by bstst** [comment]
it's all just template literals. literally:

```
return html `
      <div>
        ${this.portfolio.get('adapters').map(adapter => Adapter.new({ ...adapter }))}
      </div>
    `
```

**Comment by ged-odoo** [comment]
oh ok. cool :)
