### ISSUE TITLE
conditionally added html tag attribute

### ISSUE THREAD

**Issue by bstst** [Authman2/Mosaic#8]
How do I render a conditionally checked / unchecked checkbox input?

this does not seem to work:

```
        <input
          type="checkbox"
          onchange=${this.actions.handleChange}
          ${this.data.enabled ? 'checked' : ''}
        />
```

Checked inputs should be either `<input type="checkbox" checked" />` or `<input type="checkbox" checked="checked" />`, unchecked inputs SHOULD NOT have a `checked` attribute in any form.

**Comment by Authman2** [comment]
Coming in the next update. You will use them like regular attributes, setting their value to either true or false. They will be parsed as boolean attributes, though, so when the value is true the attribute will be present and when it is false the attribute will be removed.
